name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the first minute of every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: 'master'
          fetch-depth: 0  # Ensures all branches are fetched

      - name: Setup Git config
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'

      - name: Add upstream remote
        run: git remote add upstream https://github.com/subirkumarpaul/Subir-Max-2.git

      - name: Fetch latest changes from upstream
        run: git fetch upstream

      - name: Checkout master branch
        run: git checkout master  # Ensures the local master branch is ready

      - name: Merge upstream changes
        run: |
          git merge upstream/master --no-ff  # Allows a merge commit
          git push origin master  # Pushes the changes to your fork on GitHub
      - name: Notify via Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "Subir-Max2 > M3U files successfully synchronized! 🚀"
